### ISSUE TITLE
Trim Jupyter Notebook data

### ISSUE THREAD

**Issue by BijalBPatel** [NSLS-II-SST/rsoxs_scans#11]
Challenge: Uploading Jupyter notebooks to git can give huge file sizes because the output of cells is also synced (not just the code).

For unrelated projects. I'd addressed this by using pre-commit (https://pre-commit.com) following [the protocol here: ](https://zhauniarovich.com/post/2020/2020-06-clearing-jupyter-output/#:~:text=The%20obvious%20solution%20to%20this,Output%20%2D%3E%20Clear%20menu%20item.)

Todo: consider whether this needs follow-up at all and elaborate on process.

**Comment by BijalBPatel** [comment]
Trialing this way instead - it seems easier and doesn't require extra python packages.

https://gist.github.com/33eyes/431e3d432f73371509d176d0dfb95b6e

**Comment by BijalBPatel** [comment]
All users would need to do is download the repository and run:

`git config filter.strip-notebook-output.clean 'jupyter nbconvert --ClearOutputPreprocessor.enabled=True --to=notebook --stdin --stdout --log-level=ERROR'  `

In terminal within the repository folder

**Comment by EliotGann** [comment]
before committing, we can just remove all outputs in the jupyter menu

**Comment by BijalBPatel** [comment]
I think people will forget to do it. 
But also this is of minor concern since we only have 1 notebook in the repository. 
This is more an issue for data analysis heavy repositories. 

Now that there is a good solution documented, we can always just revisit if it becomes a problem.
