### ISSUE TITLE
Sample_Bar_template_v2023_1.1 Suggestions

### ISSUE THREAD

**Issue by BijalBPatel** [NSLS-II-SST/rsoxs_scans#17]
Suggestions for the next version of the spreadsheet based on testing 230121. All minor suggestions.

- On the "Acquisitions" Sheet, data validation for sample_id appears to be failing (I can put whatever I want and it doesn't care if it doesnt match a sample_id in the "Bar" sheet). This may get caught on dry-run. Not sure if you want it to be prevented within the excel sheet though.

-On the "Acquisitions" Sheet, suggested to change example for angles to [-10, 20,40,55,70,90] so that it makes clear how to get around excel's limitation for specifying negative values in a list. Similarly for polarization (or anywhere you might lead with a negative number in a list). May prevent emails from users.

- On the "Acquisitions" Sheet, suggested to declare default behavior for all cells. So that the 'example' cell either starts or ends with "Default: <default value> "

- On the "Acquisitions" Sheet, update the documentation on the "group" parameter "Rules" cell to match the new behavior. 

- On the "Acquisitions" Sheet, update the documentation on the "priority" parameter to mention that it is an option to specify priority each 'group' and not rank them globally.

**Comment by EliotGann** [comment]
I like these suggestions except the last one.  I think we probably need a different section of the wiki to explain priority better.  there are options to sort however you want so I wouldn't want to hard explain only one method in the sheet.

**Comment by EliotGann** [comment]
I don't think these changes warrant a new version necessarily (as in nothing warrants rejecting v1.0 from now on, right?).  i.e. they are enhancements to the user experience nothing that changes how they are read by the program.

**Comment by BijalBPatel** [comment]
Agreed - these are mostly just things to do if you are making changes for the other issue (adding more columns of values and adding a new sheet for completed scans). Depending how you code it, those may break v1.0

**Comment by BijalBPatel** [comment]
Creating  a branch to test these and suggestions harvested from the workflow meeting this week. 
It may take a week or so for me to go through and test everything/ harvest all defaults.
