### ISSUE TITLE
Bug: Error exporting sheets due ndarrays not being JSON serializable

### ISSUE THREAD

**Issue by BijalBPatel** [NSLS-II-SST/rsoxs_scans#22]
Error when trying to export sample spreadsheets.

Error text:

`An exception has occurred, use '%tb verbose' to see the full traceback.  TypeError: Object of type ndarray is not JSON serializable  See /var/log/bluesky/bluesky.log for the full traceback."), `

Fix:
```

for samp in bar:
	for acq in samp['acq_history']:
		print(acq)
		for arg in acq['arguments']:
			if isinstance(acq['arguments'][arg],np.ndarray):
acq['arguments'][arg] = list(acq['arguments'][arg])
```

**Comment by EliotGann** [comment]
Fixed in be966cf
