### ISSUE TITLE
Bug: Spreadsheet load can skip lines 1-4 if bar and acquisitions sheets are mismatched

### ISSUE THREAD

**Issue by BijalBPatel** [NSLS-II-SST/rsoxs_scans#25]
Spreadsheet load sometimes skips rows 1-4 even if sheet has no documentation rows.
 
 This is a problem because if you try to input a sheet that was automatically output, you lose the first few acquisitions.
 This bug is fixed in a pull request I'm about to make. Just documenting it here in case someone else runs into it.

**Comment by EliotGann** [comment]
to clarify, this is in the acquisition sheet?  I have not run into this somehow... I'm guessing there is something else going on in your testing?

**Comment by EliotGann** [comment]
is it perhaps when you do have documentation on the bar, but not acquisitions?

**Comment by BijalBPatel** [comment]
Yep exactly that

**Comment by BijalBPatel** [comment]
At some time last beamtime we may have ended up with a weird sheet like that. 

I think the outsheet columns didn't quite match order, so we copied over the entire output acquisitions sheet. 


The new code in the pr should check each sheet individually for documentation rows, and edge cases where some but not all of them exist etc.

**Comment by EliotGann** [comment]
ok, cool.  I will have time to check this out today I hope
