### ISSUE TITLE
Bug: NEXAFS acquisitions with 150 cycles are not allowed.

### ISSUE THREAD

**Issue by pbeaucage** [NSLS-II-SST/rsoxs_scans#27]
On the beamline, I get an error if I try to command a `do_nexafs` with `cycles=150`, but not if I invoke it with `cycles=99`.

This seems to be a pretty reasonable user request and it's not clear why the code disallows it?  Perhaps a bug but I can't find the relevant bits of the scan engine despite some effort...

**Comment by EliotGann** [comment]
fixed with ee2c7972619b56776e95194016ed075772e276e4
