### ISSUE TITLE
Feat: split a sample into two when resolving spirals

### ISSUE THREAD

**Issue by pbeaucage** [NSLS-II-SST/rsoxs_scans#30]
Frequently, a spiral scan identifies two equally viable but distinct regions of interest.  It would be nice if resolve_spirals could accept a comma-separated list of "good" points, which would be used to:

- copy.deepcopy the sample object to a new sample in the bar for each number
- set the matched location for each copy to the corresponding spiral search position
- Copy all acquisitions from the sample to its duplicate (may happen automatically)

Thanks to Lucas and Julia who came up with this idea.

**Comment by EliotGann** [comment]
a pull request for this would be welcome - it's been something I've wanted for a while

**Comment by EliotGann** [comment]
This is actually for the rsoxs reposition, not this one.  This package does not include resolve_spirals.  Can you open the issue there instead?
