### ISSUE TITLE
Configs WAXS_liquid and WAXSNEXAFS get saxs_det

### ISSUE THREAD

**Issue by BijalBPatel** [NSLS-II-SST/rsoxs_scans#6]
Currently dry run assigns any config that isn't "WAXS" the saxs detector.

https://github.com/NSLS-II-SST/rsoxs_scans/blob/a73efae8322681da7bb4c1b4d0b9f25e617a8085/rsoxs_scans/acquisition.py#L49-L52

**Comment by BijalBPatel** [comment]
My solution: (will be adopted if you accept the pull request late tonight)

https://github.com/NSLS-II-SST/rsoxs_scans/blob/5908c2b7d6b91ad87027396d680d9d7aebb894f3/rsoxs_scans/acquisition.py#L59-L65

Only question is whether you normally update the RSoXS_Main_Det for NEXAFS plans too or want to leave it as SAXS.

**Comment by EliotGann** [comment]
I think for NEXAFS, an error (or warning?) should be thrown if a rsoxs or spirals are taken…

**Comment by EliotGann** [comment]
added error checking in the notebook.  lists of valid entries are added to defaults.py
