### ISSUE TITLE
Group filter for acquisitions always takes all acquisitions

### ISSUE THREAD

**Issue by BijalBPatel** [NSLS-II-SST/rsoxs_scans#7]
Right now, dryrun_bar() behaves as if group="all" regardless of what group value is provided as a parameter. 

Problem code is likely here:

https://github.com/NSLS-II-SST/rsoxs_scans/blob/5908c2b7d6b91ad87027396d680d9d7aebb894f3/rsoxs_scans/acquisition.py#L120-L123

**Comment by BijalBPatel** [comment]
a-ha! Annotated it out:

```
# Skip this acquisition unless any of these conditions are true
   if not (group == "all" # true if user specified all to be evaluated
              or a.get("group", "all") == "all"  # true if group is 'all' or no group specified
              or a.get("group", "all") == group): # true if group is 'all' OR no group specified and user wants 'all'
       continue 
```
the middle condition: `or a.get("group", "all") == "all" ` is the problem - it evaluates to true any time the group is not specified, so acquisitions without a group specified are always set to run. This seems unintended, but should be reviewed by @EliotGann .

In the pull request I will propose a fix that allows only acquisitions with group = 'group specified by user', if the user doesnt give 'all'.

**Comment by BijalBPatel** [comment]
conditions 1 and 3 also seem redundant

**Comment by EliotGann** [comment]
This was my intent actually, but if it isn’t obvious it probably needs work.  I wanted it to be if both sides (the user running run bar, user creating sheet) agree on group to use it, but if _either_ side left group unspecified that it would default to inclusion.

**Comment by BijalBPatel** [comment]
It is clear from the excel sheet documentation- my bad, haha. I didn't read it well enough.

**Comment by BijalBPatel** [comment]
Hmm... I'm not sure if it is optimal to default blank cells to 'all''.  But its a matter of opinion. 

I feel like it will lead to a lot of having to drag down cells in excel (which always has the chance of overwriting existing entries if its a sparse column). 

- Ex: Suppose the user at the beamline adds a group of spiral scan acquisitions, but existing scans are ungrouped. Now they need to quickly assign groups to everything else in order to filter for spiral. 
- Ex: In remote operation, the users want you to re-run a subset of samples, or do a new set based on good/bad results from the previous round. But the users didn't assign groups the first time around. Now you have to manually assign groups everywhere in order to use the function. If you want to force them to the front, you need to go re-assign all the priorities.

It seems to me that if you want to leave a safety option where all scans are run irrespective of group, having the default behavior be group='all' [as it is], is sufficient. 
In that case, if the user running the beamline doesn't have agreement with those submitting the sheet for using the group function, they just dont provide a group flag.

Then, if you want to let people specify in the spreadsheet that a scan should run regardless of grouping, they can set the spreadsheet group cell to 'all'.

The code would then be: 

https://github.com/NSLS-II-SST/rsoxs_scans/blob/b5ef7e3ce21e2065849a18946e365f05295b615e/rsoxs_scans/acquisition.py#L156-L161
