### ISSUE TITLE
Test Notebook gives warnings on bar import

### ISSUE THREAD

**Issue by BijalBPatel** [NSLS-II-SST/rsoxs_scans#8]
When importing bar sheets, warnings are thrown on the excel import step. Minor concern only.

Reading sheet Bar
/srv/conda/envs/notebook/lib/python3.9/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
Reading sheet Acquisitions
/srv/conda/envs/notebook/lib/python3.9/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Data Validation extension is not supported and will be removed
  for idx, row in parser.parse():

**Comment by BijalBPatel** [comment]
This is some arcane magic that is out of scope for the moment. and anyway, warnings add color to the Jupyter window.

**Comment by EliotGann** [comment]
I think the warnings are alright.  I added a bit more basic error checking to import, but the warnings are all about extra excel functionality that we have like the conditional formatting etc.

**Comment by EliotGann** [comment]
when you export and reimport the file you don't get the warnings

**Comment by EliotGann** [comment]
fixed the warnings by removing the header and footer from the excel file, and removing userwarnings in #10
